name: webapp_lib

packages:
  - webapp_components
  - webapp_core
  - webapp_model
  - webapp_ui_commons
  - webapp_utils
  - webapp_workflow

command:
  bootstrap:
    environment:
      sdk: ">=3.5.0 <4.0.0"
    dependencies:
      sci_tercen_client:
        git:
          ref: 1.4.9
          url: https://github.com/tercen/sci_tercen_client
          path: sci_tercen_client

scripts:
  analyze:
    run: dart analyze .
    description: Run Dart analyzer in all packages

  format:
    run: dart format .
    description: Format all Dart files

  test:
    run: dart test
    description: Run tests in all packages
    packageFilters:
      dirExists: test
