name: webapp_commons
description: Common functions and codes to help generating WebApps.
version: 2.0.0-build1
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  jwt_decoder: ^2.0.1
  package_info_plus: ^8.3.0
  file_picker: ^8.0.6

  flutter:
    sdk: flutter
    
  sci_tercen_client:
    git:
      ref: 1.3.1
      url: https://github.com/tercen/sci_tercen_client
      path: sci_tercen_client
  


dev_dependencies:
  test:
  lints: ^5.0.0
  build_runner: ^2.3.3
